export const userInputs = [
  {
    id: "username",
    label: "Username",
    htmlFor: "username",
    type: "text",
    placeholder: "ironyman",
  },
  {
    id: "firstname",
    label: "First Name",
    htmlFor: "firstName",
    type: "text",
    placeholder: "Tony",
  },
  {
    id: "lastname",
    label: "Last Name",
    htmlFor: "lastName",
    type: "text",
    placeholder: "Stank",
  },
  {
    id: "email",
    label: "Email",
    htmlFor: "email",
    type: "email",
    placeholder: "tony@starkindustries.com",
  },
  {
    id: "phone",
    label: "Phone",
    htmlFor: "phone",
    type: "phone",
    placeholder: "+1 234 567 89",
  },
  {
    id: "password",
    label: "Password",
    htmlFor: "password",
    type: "password",
  },
  {
    id: "confirmpassword",
    label: "Confirm Password",
    htmlFor: "confirm-password",
    type: "password",
  },
  {
    id: "address",
    label: "Address",
    htmlFor: "address",
    type: "text",
    placeholder: "Loki Street, Stark Colony, NYC",
  },
  {
    id: "country",
    label: "Country",
    htmlFor: "country",
    type: "text",
    placeholder: "Assgardpur",
  },
];

export const productInputs = [
  {
    id: "name",
    label: "Product Name",
    htmlFor: "name",
    type: "text",
    placeholder: "Apple Macbook Pro",
  },
  {
    id: "description",
    label: "Product Description",
    htmlFor: "description",
    type: "text",
    placeholder: "Description",
  },
  {
    id: "category",
    label: "Category",
    htmlFor: "category",
    type: "text",
    placeholder: "Computers",
  },
  {
    id: "price",
    label: "Price",
    htmlFor: "price",
    type: "number",
    placeholder: "100",
  },
  {
    id: "stock",
    label: "Stock",
    htmlFor: "stock",
    type: "number",
    placeholder: "in stock",
  },
  {
    id: "status",
    label: "Status",
    htmlFor: "status",
    type: "text",
    placeholder: "active",
  },
];

export const orderInputs = [
  {
    id: "item_name",
    label: "Item",
    htmlFor: "item",
    type: "text",
    placeholder: "Apple Macbook Pro",
  },
  {
    id: "customer_name",
    label: "Customer Name",
    htmlFor: "customername",
    type: "text",
    placeholder: "Tony Stark",
  },
  {
    id: "customer_email",
    label: "Customer Email",
    htmlFor: "customeremail",
    type: "email",
    placeholder: "tonystank@avengers.com",
  },
  {
    id: "customer_phone",
    label: "Customer Phone",
    htmlFor: "customerphone",
    type: "phone",
    placeholder: "+91 888-888-8888",
  },
  {
    id: "customer_address",
    label: "Customer Address",
    htmlFor: "customeraddress",
    type: "text",
    placeholder: "avengers tower, nyc",
  },
  {
    id: "category",
    label: "Category",
    htmlFor: "category",
    type: "text",
    placeholder: "Computers",
  },
  {
    id: "price",
    label: "Price",
    htmlFor: "price",
    type: "number",
    placeholder: "100",
  },
  {
    id: "quantity",
    label: "Quantity",
    htmlFor: "quantity",
    type: "number",
    placeholder: "10",
  },
  {
    id: "total_amount",
    label: "Total Amount",
    htmlFor: "totalamount",
    type: "number",
    placeholder: "1000",
  },
];
